swapp/urls.py
from django.urls import path
from . import views
from .views import HomePageView, SearchResultsView
urlpatterns = [
    path("",views.index,name="index"),
    path("post/<slug>",views.post,name="post"),
    path("search/", SearchResultsView.as_view(), name="search_results"),
]

swproj/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("swapp.urls"))
]
urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

swapp/models.py
from django.db import models
from imagekit.models import ProcessedImageField,ImageSpecField
from imagekit.processors import ResizeToFit
from django.core.exceptions import ValidationError
import os
from embed_video.fields import EmbedVideoField
from django.utils.html import mark_safe

def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]  # Extracts the file extension
    valid_extensions = ['.mp4', '.webm', '.ogg', '.mov', '.avi']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Unsupported file extension.')


class BlogPost(models.Model):
    
    title = models.CharField(max_length=200)
    content = models.TextField()
    slug = models.SlugField(blank=True)
    image_thumbnail = models.ImageField()
    imageopt = ImageSpecField(source='image_thumbnail',processors=[ResizeToFit(600,600)],
                                           format='JPEG',
                                           options={'quality': 90},
                                           )
    date = models.DateField()
    rank = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ("-rank","-date")


class BlogPostPhoto(models.Model):
    blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE, null=True)
   
    video = models.FileField(blank=True, validators=[validate_file_extension])
    embed_youtube = EmbedVideoField(blank=True)
    rank = models.IntegerField(default=0)

    class Meta:
        ordering = ("rank","id")

class PhotoBatchUpload(models.Model):
    blog_post = models.ForeignKey(BlogPost, related_name='photos', on_delete=models.CASCADE)
    image = models.ImageField()
    imageopt = ImageSpecField(source='image',processors=[ResizeToFit(600,600)],
                                           format='JPEG',
                                           options={'quality': 90},
                                           )
    rank = models.IntegerField(default=0)

    def thumbnail(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" width="50" height="50" />')
        return ""
    thumbnail.short_description = 'preview'



    def __str__(self):
        return f"Photo for {self.blog_post.title}"
    class Meta:
        ordering = ("rank","id")

swapp/forms.py
from django import forms
from .models import PhotoBatchUpload

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleImageField(forms.FileField):
    widget = MultipleFileInput

    def to_python(self, data):
        if not data:
            return []
        if isinstance(data, list):
            return data
        return [data]

    def validate(self, data):
        if not self.required and not data:
            return
        super().validate(data)
        for item in data:
            super().validate(item)

    def run_validators(self, data):
        errors = []
        for item in data:
            try:
                super().run_validators(item)
            except forms.ValidationError as error:
                errors.extend(error.error_list)
        if errors:
            raise forms.ValidationError(errors)

class PhotoBatchUploadForm(forms.ModelForm):
    images = MultipleImageField(required=False)

    class Meta:
        model = PhotoBatchUpload
        fields = []

    def save(self, commit=True):
        instance = super().save(commit=False)
        images = self.cleaned_data.get('images')
        if commit:
            instance.save()  # Save the instance to get an ID
            if images:
                for image in images:
                    PhotoBatchUpload.objects.create(blog_post=instance.blog_post, image=image)
        return instance

swapp/views.py
from django.shortcuts import render
from .models import BlogPost, BlogPostPhoto
from collections import defaultdict
import pprint
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    blogposts = BlogPost.objects.order_by("-rank")

    post_list = BlogPost.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(post_list, 12)
    try:
        blogposts = paginator.page(page)
    except PageNotAnInteger:
        blogposts = paginator.page(1)
    except EmptyPage:
        blogposts = paginator.page(paginator.num_pages)


    context = {
        "blogposts": blogposts,
    }

    return render(request, "index.html", context)


def post(request,slug):
    blogposts = BlogPost.objects.order_by("-id")
    blogpost = BlogPost.objects.get(slug=slug)

    context = {
        "blogposts": blogposts,
        "blogpost": blogpost,

    }

    return render(request, "post.html", context)

class HomePageView(TemplateView):
    template_name = 'index.html'

class SearchResultsView(ListView):
    model = BlogPost
    template_name = 'search_results.html'
    

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query is not None:
            object_list = BlogPost.objects.filter(
            Q(title__icontains=query) | Q(content__icontains=query) | Q(date__icontains=query) 
            )

            
        return object_list
    

swapp/templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}

  <div class="table-container">
    {% for b in blogposts %}
    <a href="{% url 'post' b.slug %}" style="color:blue;text-decoration: none;cursor:pointer;">
      <div class="table-item">
        <center>
          <a href="{% url 'post' b.slug %}" style="color:black;text-decoration: none;cursor:pointer;">
            {% if forloop.first %}
            {% if not blogposts.has_previous %}
              <img src="{% static 'new.gif' %}" width="30px" style="vertical-align: middle;" />
              {% endif %}
              {% endif %}
            <i><small style="font-size: 10px; color:blue;">{{ b.date|date:'F j Y' }}</small></i>
            <br />
            <b><font size="5" style="background-color: white;">{{ b.title }}</font></b>
            <br />
            <img src="{{ b.imageopt.url }}" width="150px" />
            <br /><br />
          </a>
        </center>
      </div>
    </a>
    {% endfor %}
  </div>

  <br>
  <div id="pagination" width="222px">

      {% if blogposts.has_previous %}
        <a href="?page={{ blogposts.previous_page_number }}">previous</a> |
      {% else %}
        <span>previous</span> |
      {% endif %}
      {% for i in blogposts.paginator.page_range %}
        {% if blogposts.number == i %}
          <b><span class="paginActi">{{ i }}</span></b> |
        {% else %}
          <a href="?page={{ i }}">{{ i }}</a> |
        {% endif %}
      {% endfor %}
      {% if blogposts.has_next %}
        <a href="?page={{ blogposts.next_page_number }}">next</a>
      {% else %}
        <span>next</span>
      {% endif %}


  </div>
{% endblock %}

swapp/templates/layout.html
{% load static %}
{% load tz %}
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="stylesheet" href="{% static 'style_final.css' %}" />
    <link rel="icon" href="{% static 'favicon.png' %}" />
    <title>SW NEWS</title>
    <meta name="keywords" content="news, saintwoods, SW" />
    <meta name="author" content="Saintwoods" />
    <meta name="description" content="News by Saintwoods" />
    <meta property="og:title" content="SW NEWS" />
    <meta property="og:type" content="news website" />
    <meta property="og:url" content="news.saintwoods.com" />
    <meta property="og:image" content="{% static 'sw-gif-3.gif' %}" />
    <meta property="og:site_name" content="SW NEWS" />
    <meta property="og:description" content="News by Saintwoods" />
    <style>
      body::before {
        content: "";
        background-image: url({% static 'cloud_tile.gif' %});
        background-repeat: repeat;
        opacity: 0.4; 
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
    }
    </style>
  </head>
  <body>
    <center>
      <br />
      <small>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
      </small>
      <br />
      <a href="/">
        <img src="{% static 'bar27.gif' %}" class="bar" />
        <br />
        <img src="{% static 'satellites-04.gif' %}" class="satellite" />
        <img src="{% static 'sw-gif-3.gif' %}" class="swnews" />
        <img src="{% static 'globe.gif' %}" class="globe" />
        <br />
        <img src="{% static 'bar27.gif' %}" class="bar" /> <br />
      </a>
      <small>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
        <span style="background-color: yellow;color:red" class="star">★</span>
      </small>
      <br />
      <br />

      <div class="container-div">
        <div class="item-div">
          <img src="{% static 'icon-vodka.png' %}" width="40px" />
          <br />
          <font size="-2">
            <a href="https://vodkabysaintwoods.com/" style="color:blue;">Vodka by<br />Saintwoods</a>
          </font>
        </div>

        <div class="item-div">
          <b><span id="local-time" style="background-color: black;color:white;" class="blinking-text"></span></b>
          <br />
          <br />
          <form action="/search/" method="get">
            <img src="{% static 'search15.gif' %}" style="vertical-align: middle;image-rendering: pixelated;" />
            <input name="q" type="text" placeholder="search keyword" />
            <button type="submit">Search</button><br />
          </form>
        </div>

        <div class="item-div">
          <img src="{% static 'icon-sw.png' %}" width="40px" />
          <br />
          <font size="-2">
            <a href="https://saintwoods.com/" style="color:blue;">Saintwoods<br />Website</a>
          </font>
        </div>
      </div>

      {% block content %}

      {% endblock %}

      <br />
      <img src="{% static 'barverm.gif' %}" width="333px" />
      <br />
      <br />
      
      <div style="background-color:black; color:white;width:270px;border: solid 2px white;">
        <img src="{% static 'rainbow_thinline.gif' %}" width="270px" /><br />
        <font size="-2">
          © {% now 'Y' %} Copyright © <a href="https://saintwoods.com/" target="_blank" style=" color:white;">SAINTWOODS {% now 'Y' %} ®</a> All rights reserved.
          <br />
          No part of this site maybe used or reproduced in whole or in part
          <br />
          without the written consent of Copyright Owner
        </font>
        <br />
        
        <img src="{% static 'rainbow_thinline.gif' %}" width="270px" />
      </div>
    </center>
    <script src="{% static 'time.js' %}"></script>
  </body>
</html>

swapp/templates/post.html
{% extends 'layout.html' %}
{% load static %}
{% load embed_video_tags %}
{% block content %}
  <small style="color:blue;"><i>{{ blogpost.date }}</i></small><br />
  <span><b><font size="6" style="background-color: white;color: black;">{{ blogpost.title }}</font></b></span><br />

  <p style=" text-align: justify;max-width: 600px;width:90vw;background-color: aliceblue;">{{ blogpost.content|urlize|linebreaksbr }}</p>

  {% if blogpost.blogpostphoto_set.count > 0 %}
    {% for p in blogpost.blogpostphoto_set.all %}
      {% if p.imageopt %}
        <img src="{{ p.imageopt.url }}" style="max-width: 600px;width:90vw;" />
      {% endif %}

      {% if p.video %}
        <video style="max-width: 600px;width:90vw;" controls>
          <source src="{{ p.video.url }}" />
        </video>
        <br><br>
      {% endif %}

      {% if p.embed_youtube %}
 
          {% video p.embed_youtube '333x250' %}
        <br><br>
      {% endif %}

    {% endfor %}
  {% endif %}




  {% if blogpost.photos.count > 0 %}
  <div class="masonry-container">
      {% for photo in blogpost.photos.all %}
          {% if photo.image %}
          <div class="masonry-item"><img src="{{ photo.image.url }}" ></div>
          {% endif %}
      {% endfor %}
  </div>
{% endif %}

  <br />
{% endblock %}

swapp/templates/search_results.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}

  {% if object_list.count == 0 %}
    <h3><span style="background-color: blue;color:cyan ;">No Result</span></h3>
  {% elif object_list.count == 1 %}
    <h3><span style="background-color: blue;color:cyan ;">{{ object_list.count }} Result</span></h3>
  {% else %}
    <h3><span style="background-color: blue;color:cyan ;">{{ object_list.count }} Results</span></h3>
  {% endif %}
  <div class="table-container">
    {% for b in object_list %}
    <a href="{% url 'post' b.slug %}" style="color:black;text-decoration: none;cursor:pointer;">
      <div class="table-item">
        <center>
          <a href="{% url 'post' b.slug %}" style="color:black;text-decoration: none;cursor:pointer;">
            <i><small style="font-size: 10px; color:blue;">{{ b.date|date:'F j Y' }}</small></i>
            <br />
            <b><font size="5" style="background-color: white;">{{ b.title }}</font></b>
            <br />
            <img src="{{ b.imageopt.url }}" width="150px" />
            <br /><br />
          </a>
        </center>
      </div>
    </a>
    {% endfor %}
  </div>
  <br>
  <div id="pagination" width="222px">
    {% if blogposts.has_previous %}
      <a href="?page={{ blogposts.previous_page_number }}">previous</a> |
    {% else %}
      <span>previous</span> |
    {% endif %}
    {% for i in blogposts.paginator.page_range %}
      {% if blogposts.number == i %}
        <span class="paginActi">{{ i }}</span> |
      {% else %}
        <a href="?page={{ i }}">{{ i }}</a> |
      {% endif %}
    {% endfor %}
    {% if blogposts.has_next %}
      <a href="?page={{ blogposts.next_page_number }}">next</a>
    {% else %}
      <span>next</span>
    {% endif %}
  </div>
{% endblock %}